[profile.default]
solc = '0.8.28'
evm_version = 'cancun'
optimizer_runs = 200
via_ir = true
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.ci_sizes]

[fuzz]
runs = 4096

[invariant]
runs = 1024
depth = 100
fail_on_revert = false

[lint]
exclude_lints = ["pascal-case-struct", "mixed-case-variable"]
[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true

[rpc_endpoints]
ethereum = "${RPC_ETHEREUM_MAINNET}"
